site_name: SciANN Documentation

# theme: cinder
theme: readthedocs
  # name: null
  # custom_dir: theme
  # static_templates:
  #   - 404.html
  # include_search_page: true
  # search_index_only: false
  # highlightjs: true
  # hljs_languages: []
  # include_homepage_in_sidebar: true
  # prev_next_buttons_location: bottom
  # navigation_depth: 4
  # titles_only: false
  # sticky_navigation: true
  # collapse_navigation: true


docs_dir: sources
repo_url: http://github.com/sciann/sciann
site_url: http://sciann.com/
site_description: 'Documentation for Keras, the Python Deep Learning library.'

# Math markdown. 
markdown_extensions: [math]
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']

nav:
- Home: index.md
- Why use SciANN: why-use-sciann.md
- Getting started:
  - Guide to SciANN model: getting-started/scimodel-guide.md
  - Guide to Functional: getting-started/functional-guide.md
- Functionals: functionals.md
- SciModels: scimodels.md
- Variables: variables.md
- Constraints: constraints.md
